### ISSUE TITLE
Modifying for HiDPI?

### ISSUE THREAD

**Issue by iddm** [worron/redflat#30]
What should we change in the library so that it supports HiDPI monitors? For example, my dpi is twice as big as usual (192 instead of 96) . Last time I modified all the constants by multiplying it twice but is there more elegant method?

**Comment by worron** [comment]
Long story short, custom themes can handle hidpi problem and I don't see a need for any additional mechanic. Constants modifying is pretty inelegant, but very flexible way to deal with appearance.

Every widgets size and proportions can be changed with themes. I admit that fixing every single widget style separately is pain, but as was said, it's very flexible. Alternative way will be add some multiplier to default sizes, but user can do this by himself in custom theme. Moreover, in my view there are no default widget sizes. Style constants in library only to demonstrate one of possible appearance for every widget. Thin or thick panel, compact or bulky widgets can be defined by user part of config, so I prefer not to  complicate styling with some dpi scaling.

Also if you met some widgets appearance parameter which hard coded and can't be changed with theme, just report, I'll try to fix it.

**Comment by iddm** [comment]
I have fixed this manually. `beatiful.xresources` provides `apply_dpi` function which calculates new value. Applying it to every number in the `themelua` scales everything properly.

https://github.com/vityafx/awesome-config/commit/1082afe710966f5a831d10b5b67fc07530862463

Probably it is better to do this in the upstream because it will work properly everywhere anyway.

**Comment by worron** [comment]
Yes, this is what I meant, use scale factor in user theme if needed.

Still have some concerns about using `beautiful.xresources.apply_dpi` in upstream right now. May be I will return to this point in future.

**Comment by worron** [comment]
After careful thought, I have decided to not change current theme model. Any dpi modifications are left to the user side.
